POST https://node-do-zero-6o4l.onrender.com/videos
Content-Type:  application/json

{
    "title": "Video 04 - node.js",
    "description": "Meu quarto",
    "duration": "30"
}

###
GET https://node-do-zero-6o4l.onrender.com/videos

###
GET https://node-do-zero-6o4l.onrender.com/videos?search=video

###
PUT https://node-do-zero-6o4l.onrender.com/videos/360dddce-7f64-4e5d-9e80-1f36449576b6
Content-Type:  application/json

{
    "title": "Video 01",
    "description": "Meu primeiro modificado",
    "duration": "30"
}

###
DELETE https://node-do-zero-6o4l.onrender.com/videos/360dddce-7f64-4e5d-9e80-1f36449576b6