POST http://localhost:3333/videos
Content-Type:  application/json

{
    "title": "Video 03 - node.js",
    "description": "Meu primeiro",
    "duration": "30"
}

###
GET http://localhost:3333/videos

###
GET http://localhost:3333/videos?search=video

###
PUT http://localhost:3333/videos/a701536a-204b-4ced-ad9c-34803bd189bf
Content-Type:  application/json

{
    "title": "Video 01",
    "description": "Meu primeiro modificado",
    "duration": "30"
}

###
DELETE http://localhost:3333/videos/a701536a-204b-4ced-ad9c-34803bd189bf